### ISSUE TITLE
Bundle funktioniert nicht bei den loadservices

### ISSUE THREAD

**Issue by neledahlhues** [conterra/mapapps-popups-action-maximize#1]

**Comment by matthiasstein** [comment]
Dies ist kein Fehler dieses Bundles. Hinzugeladene Dienste verwenden das Standard-Popup, solange dieses aktiviert ist. Dieses Popup kann allerdings aktuell Custom Actions anzeigen. Diese Anforderung wurde unter MAPAPPS-6212 erfasst.
