### ISSUE TITLE
Bundle funktioniert nicht bei WMS Layer

### ISSUE THREAD

**Issue by gadgec** [conterra/mapapps-popups-action-maximize#3]
Custom Action erscheint nur bei Layern vom type: AGS_DYNAMIC, aber nicht bei type: WMS

**Comment by matthiasstein** [comment]
Die ist ein map.apps Bug, der unter der Nummer MAPAPPS-5711 erfasst ist.

**Comment by matthiasstein** [comment]
Da der Task MAPAPPS-5711 mit map.apps 4.15 geschlossen wurde, schließe ich diesen Issue.
